# Generated by Django 5.1.7 on 2025-03-21 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='injury',
            name='recommendations',
            field=models.TextField(default='Консултирайте се с медицинско лице.'),
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symptoms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_api.symptom')),
            ],
        ),
    ]
