# Generated by Django 5.1.7 on 2025-03-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_api', '0002_place_alter_injury_recommendations_symptom_cause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='key',
        ),
        migrations.AddField(
            model_name='symptom',
            name='cause',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_api.cause'),
        ),
    ]
