# Generated by Django 5.1.7 on 2025-03-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_api', '0002_symptom_alter_injury_recommendations_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='key',
            field=models.CharField(max_length=10),
        ),
    ]
