# Generated by Django 5.1.6 on 2025-03-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_active_member_email_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
    ]
